# www_profile_co_th
services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - /var/www/wordpress:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf  # Add this line
    depends_on:
      - php
    networks:
      - main_public

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - /var/www/wordpress:/var/www/html
    networks:
      - main_public

networks:
  main_public:
    external: true